# Change these first
owner: taitopia-dev # Your GitHub organization or username, where this repository lives
repo: taitopia-status-page # The name of this repository
user-agent: taitopia-status-probe

sites:
  - name: Taitopia Web Application
    url: https://app.taitopia.design
    method: GET

  - name: Taitopia Workflow Infrastructure
    url: https://status-api.taitopia.design/health/workflow
    method: GET
    __dangerous__body_down: '"status":"down"'
    __dangerous__body_degraded: '"status":"degraded"'

  - name: Taitopia Asset Management Service
    url: https://status-api.taitopia.design/health/tortilla
    method: GET
    __dangerous__body_down: '"status":"down"'
    __dangerous__body_degraded: '"status":"degraded"'

  - name: Taitopia User Management Service
    url: https://status-api.taitopia.design/health/salsa
    method: GET
    __dangerous__body_down: '"status":"down"'
    __dangerous__body_degraded: '"status":"degraded"'

  - name: Taitopia Render Queue Status
    url: https://status-api.taitopia.design/health/camote
    method: GET
    __dangerous__body_down: '"status":"down"'
    __dangerous__body_degraded: '"status":"degraded"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.taitopia.design
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.taitopia.design/taitopia.design/favicon/apple-touch-icon.png
  favicon: https://cdn.taitopia.design/taitopia.design/favicon/apple-touch-icon.png
  name: Taitopia Status Page
  introTitle: "This is the status page of some of the **Taitopia Design** public-facing services"
  introMessage: Welcome to the status page of Taitopia, we are sorry if you run into incidents due to downtime of our services!
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: About Us
      href: https://taitopia.design
    - title: Join Discord
      href: https://discord.gg/3GsJxnduK4

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  # every 6 hours
  uptime: "0 */6 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
